<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="harsimrandhanoa" name="Second Class" tests="2" failures="1" timestamp="21 Apr 2016 16:01:13 GMT" time="0.009" errors="0">
  <testcase name="Test" time="0.0" classname="testng.SecondTest"/>
  <testcase name="checkResults" time="0.005" classname="testng.SecondTest">
    <failure type="java.lang.AssertionError" message="Results are again not good expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Results are again not good expected [false] but found [true]
	at testng.SecondTest.checkResults(SecondTest.java:48)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- checkResults -->
</testsuite> <!-- Second Class -->
